---
become_override: false

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

OCP_AMP_ADMIN_ID: api0

ocp_user_needs_quota: true

RESUME_CONTROL_PLANE_GWS: true

# dedicated API Manager
quota_requests_cpu_dedicated: 4
quota_limits_cpu_dedicated: 12            # Safe to over-provision on CPU; at any given time, API Manager for test purposes really only needs about 4 CPU total
quota_requests_memory_dedicated: '16Gi'
quota_limits_memory_dedicated: '24Gi'

# shared API Manager
quota_requests_cpu_shared: 20
quota_limits_cpu_shared: 30
quota_requests_memory_shared: '20Gi'
quota_limits_memory_shared: '30Gi'


quota_configmaps: 15
quota_pods: 30
quota_persistentvolumeclaims: 10
quota_services: 150
quota_secrets: 150
quota_requests_storage: 40Gi


build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

# Wildard DNS of OCP cluster environment
#ocp_apps_domain: "apps-{{ subdomain_base }}"          # Ravello environment
ocp_apps_domain: "apps.{{ subdomain_base }}"           # All other OCP environments


lab_name: 3scale-mt
API_MANAGER_NS: "{{lab_name}}-{{OCP_AMP_ADMIN_ID}}"

is_shared_cluster: false

# Use this for 3scale AMP on shared cluster
threescale_template_shared: https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.6.0.GA/amp/amp.yml

# Use this for 3scale AMP on dedicated single VM
threescale_template_dedicated: https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.6.0.GA/amp/amp.yml

work_dir: "/tmp/{{API_MANAGER_NS}}"
modified_template_path: "{{work_dir}}/amp.yml"

amp_admin_passwd: admin
amp_master_passwd: master
master_access_token: wtqhhsly
default_tenant_username: t1
default_tenant_name: "{{ default_tenant_username }}-{{ API_MANAGER_NS }}"
default_tenant_access_token: 3832cnj371woiduh

# Output and log files to be added to invokers home directory
new_app_output_dir: "{{ lookup('env','HOME') }}/provisioning_output/{{subdomain_base}}"
new_app_output: "{{new_app_output_dir}}/{{API_MANAGER_NS}}-out.log"

# smtp
smtp_host: "smtp.sendgrid.net"
smtp_port: 587
smtp_authentication: plain
smtp_userid: changeme
smtp_passwd: changeme


######   new tenants    #######

# base name of OCP users that will have access to their corresponding API Mgmt related projects
ocp_user_name_base: ocp

# initial base name of 3scale API administrator of each tenant; ie: api1, api2, api3 ...
#
# default is "api" so that it is intentionally different than the user names commonly found in the following OCP OAuth providers:
#   1)  htpassword:  base name is commonly "user"
#   2)  github.com:gpe-mw-ansible-org/rh-sso-multi-realm : base name is commonly "ocp"
#
# If afterwards 3scale Admin Portal is configured to leverage one of the two OCP OAuth providers, this change will be evident because the admin user names will have changed
#   ie;  from api1  to ocp1
tenant_admin_user_name_base: api
tenantAdminPasswd: admin

use_padded_tenant_numbers: true

create_gws_with_each_tenant: "true"

only_delete_tenants: "{{REMOVE_TENANTS_ONLY}}"

tenant_api_gw_template_url: "https://raw.githubusercontent.com/gpe-mw-training/3scale_onpremise_implementation_labs/master/resources/rhte/3scale-apicast.yml"
tenant_api_wildcard_gw_template_url: "https://raw.githubusercontent.com/gpe-mw-training/3scale_onpremise_implementation_labs/master/resources/rhte/3scale-wc-router.yml"

adminEmailUser: changeme
adminEmailDomain: "changeme.com"

tenant_output_dir: "{{new_app_output_dir}}/tenants_{{API_MANAGER_NS}}"
tenant_provisioning_log_file: "tenant_provisioning.log"
start_tenant: 1
end_tenant: 1
tenant_loop_delay: 15
tenant_provisioning_results_file: "tenant_info_file_{{start_tenant}}_{{end_tenant}}.txt"

# TO_DO:  Must current be set to true
#   Otherwise, the following exception will be thrown in API gateway:
#       failed to get list of services: invalid status: 403 (Forbidden) url: http://system-master.3scale-mt-api0:3000/admin/api/services.json, context: ngx.timer
#       configuration request sent: http://system-master.3scale-mt-api0:3000/admin/api/nginx/spec.json, context: ngx.timer
tenant_reference_external_api_mgmt_routes: "true"




ocp_username: adm2
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 25
quota_limits_cpu: 25

quota_requests_memory: '12Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 15
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 150
quota_secrets: 150
quota_requests_storage: 50Gi

lab_name: api-lifecycle
ocp_project: "{{lab_name}}"

build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 20
deploy_status_delay: 20

OPENSHIFT_MASTER: "https://master.{{subdomain_base}}"

SSO_HOSTNAME_HTTP: "sso-unsecured.apps.{{subdomain_base}}"
SSO_HOSTNAME_HTTPS: "sso.apps.{{subdomain_base}}"
SSO_ADMIN_USERNAME: admin
SSO_ADMIN_PASSWORD: password


APICURIO_UI_ROUTE: "apicurio-studio.apps.{{subdomain_base}}"
APICURIO_API_ROUTE: "apicurio-studio-api.apps.{{subdomain_base}}"
APICURIO_WS_ROUTE: "apicurio-studio-ws.apps.{{subdomain_base}}"
MICROCKS_ROUTE_HOSTNAME: "microcks.apps.{{subdomain_base}}"
KEYCLOAK_ROUTE_HOSTNAME: "http://{{SSO_HOSTNAME_HTTP}}/auth"

OPENSHIFT_OAUTH_CLIENT_NAME: apilifecycle
project_description: "Lab Infrastructure project for SSO, Microcks & Apicurio Studio."
APPLICATION_NAME: "quoting"
SOURCE_REPOSITORY_URL: "https://github.com/gpe-mw-training/rhte-api-as-business-labs"
SOURCE_REPOSITORY_REF: "master"
CONTEXT_DIR: "services/InsuranceQuoting"

apibiz_url: https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/

persistent_sso_template_url: "{{apibiz_url}}/sso72-x509-mysql-persistent.json"
sso_oauth_realm_template_url: "{{apibiz_url}}/sso-oauth-realm-templates.yml"
